name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab 
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          EMAIL:    ${{ secrets.EMAIL }}
          EMAIL_KEY: ${{ secrets.EMAIL_KEY }}
        run: git push --force https://Dhruv2508:$HF_TOKEN$EMAIL$EMAIL_KEY@huggingface.co/spaces/Dhruv2508/Trip_planner main
          